/**
 * LinkedIn Connect — "Sign In with LinkedIn using OpenID Connect".
 *
 * This is IDENTITY ONLY (`openid profile email` scopes). LinkedIn has no
 * public API for job search or application submission for third-party apps,
 * so this service never touches jobs or applications — it only proves "this
 * user is who they say they are on LinkedIn" and stores that connection so
 * the Application Copilot can show it as persistent account-level state.
 *
 * Important product-tier caveat: this OIDC product does NOT issue a refresh
 * token. `encrypted_refresh_token` will almost always be null in practice —
 * the honest UX when a token expires (~60 days) is "reconnect", never
 * "auto-refreshed". Don't build UI copy that promises silent renewal.
 */
import { db } from '../config/db';
import { env } from '../config/env';
import { httpError } from '../types';
import { encryptSecret, decryptSecret } from './crypto.service';

const AUTHORIZATION_ENDPOINT = 'https://www.linkedin.com/oauth/v2/authorization';
const TOKEN_ENDPOINT = 'https://www.linkedin.com/oauth/v2/accessToken';
const USERINFO_ENDPOINT = 'https://api.linkedin.com/v2/userinfo';
const SCOPE = 'openid profile email';

function requireConfig(): { clientId: string; clientSecret: string; redirectUri: string } {
  const { clientId, clientSecret, redirectUri } = env.linkedin;
  if (!clientId || !clientSecret || !redirectUri) {
    throw httpError(503, 'LinkedIn Connect is not configured on this server');
  }
  return { clientId, clientSecret, redirectUri };
}

interface TokenResponse {
  access_token: string;
  expires_in: number;
  refresh_token?: string;
  refresh_token_expires_in?: number;
  scope?: string;
}

interface UserInfoResponse {
  sub: string;
  name?: string;
  email?: string;
}

export type LinkedInConnectionStatus = 'not_connected' | 'connected' | 'reauthorization_required';

export interface LinkedInConnectionSummary {
  status: LinkedInConnectionStatus;
  linkedinMemberId?: string;
  connectedAt?: string;
  lastVerifiedAt?: string | null;
  accessTokenExpiresAt?: string;
}

interface ConnectionRow {
  id: string;
  linkedin_member_id: string;
  encrypted_access_token: string;
  encrypted_refresh_token: string | null;
  access_token_expires_at: string;
  refresh_token_expires_at: string | null;
  scopes: string[];
  status: 'connected' | 'reauthorization_required' | 'disconnected';
  connected_at: string;
  last_verified_at: string | null;
}

/** Builds the LinkedIn authorization URL. `state` is generated by the caller
 *  (controller) and bound to the user via a signed httpOnly cookie — never
 *  trust the `state` query param alone on the callback. */
export function buildAuthorizationUrl(state: string): string {
  const { clientId, redirectUri } = requireConfig();
  const params = new URLSearchParams({
    response_type: 'code',
    client_id: clientId,
    redirect_uri: redirectUri,
    state,
    scope: SCOPE,
  });
  return `${AUTHORIZATION_ENDPOINT}?${params.toString()}`;
}

async function exchangeCodeForTokens(code: string): Promise<TokenResponse> {
  const { clientId, clientSecret, redirectUri } = requireConfig();
  const body = new URLSearchParams({
    grant_type: 'authorization_code',
    code,
    redirect_uri: redirectUri,
    client_id: clientId,
    client_secret: clientSecret,
  });
  const resp = await fetch(TOKEN_ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: body.toString(),
  });
  if (!resp.ok) {
    throw httpError(502, `LinkedIn token exchange failed (${resp.status})`);
  }
  return (await resp.json()) as TokenResponse;
}

async function fetchUserInfo(accessToken: string): Promise<UserInfoResponse> {
  const resp = await fetch(USERINFO_ENDPOINT, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });
  if (resp.status === 401) throw httpError(401, 'LinkedIn access token rejected');
  if (!resp.ok) throw httpError(502, `LinkedIn userinfo request failed (${resp.status})`);
  return (await resp.json()) as UserInfoResponse;
}

/** Completes the OAuth handshake for `userId` and upserts `linkedin_connections`. */
export async function handleCallback(
  userId: string,
  code: string,
): Promise<LinkedInConnectionSummary> {
  const tokens = await exchangeCodeForTokens(code);
  const info = await fetchUserInfo(tokens.access_token);

  const now = Date.now();
  const accessTokenExpiresAt = new Date(now + tokens.expires_in * 1000).toISOString();
  const refreshTokenExpiresAt = tokens.refresh_token_expires_in
    ? new Date(now + tokens.refresh_token_expires_in * 1000).toISOString()
    : null;

  const { error } = await db.from('linkedin_connections').upsert(
    {
      user_id: userId,
      linkedin_member_id: info.sub,
      encrypted_access_token: encryptSecret(tokens.access_token),
      encrypted_refresh_token: tokens.refresh_token ? encryptSecret(tokens.refresh_token) : null,
      access_token_expires_at: accessTokenExpiresAt,
      refresh_token_expires_at: refreshTokenExpiresAt,
      scopes: (tokens.scope ?? SCOPE).split(' ').filter(Boolean),
      status: 'connected',
      connected_at: new Date(now).toISOString(),
      last_verified_at: new Date(now).toISOString(),
      disconnected_at: null,
    },
    { onConflict: 'user_id' },
  );
  if (error) throw httpError(500, 'Failed to save LinkedIn connection');

  return {
    status: 'connected',
    linkedinMemberId: info.sub,
    connectedAt: new Date(now).toISOString(),
    lastVerifiedAt: new Date(now).toISOString(),
    accessTokenExpiresAt,
  };
}

/** DB-only read — no outbound call to LinkedIn. Cheap status for UI rendering. */
export async function getConnectionStatus(userId: string): Promise<LinkedInConnectionSummary> {
  const { data } = await db
    .from('linkedin_connections')
    .select('linkedin_member_id, access_token_expires_at, status, connected_at, last_verified_at')
    .eq('user_id', userId)
    .maybeSingle();
  const row = data as Pick<
    ConnectionRow,
    | 'linkedin_member_id'
    | 'access_token_expires_at'
    | 'status'
    | 'connected_at'
    | 'last_verified_at'
  > | null;
  if (!row || row.status === 'disconnected') return { status: 'not_connected' };

  const expired = new Date(row.access_token_expires_at).getTime() <= Date.now();
  return {
    status:
      row.status === 'reauthorization_required' || expired
        ? 'reauthorization_required'
        : 'connected',
    linkedinMemberId: row.linkedin_member_id,
    connectedAt: row.connected_at,
    lastVerifiedAt: row.last_verified_at,
    accessTokenExpiresAt: row.access_token_expires_at,
  };
}

/** Actively calls LinkedIn's userinfo endpoint to confirm the stored token
 *  still works. Marks the row `reauthorization_required` on a 401 instead of
 *  leaving stale "connected" state. Used lazily by the Application Copilot
 *  right before it lets a consultant proceed to the review/confirm step. */
export async function verifyConnection(userId: string): Promise<boolean> {
  const { data } = await db
    .from('linkedin_connections')
    .select('id, encrypted_access_token, status')
    .eq('user_id', userId)
    .maybeSingle();
  const row = data as Pick<ConnectionRow, 'id' | 'encrypted_access_token' | 'status'> | null;
  if (!row || row.status === 'disconnected') return false;

  try {
    await fetchUserInfo(decryptSecret(row.encrypted_access_token));
    await db
      .from('linkedin_connections')
      .update({ last_verified_at: new Date().toISOString(), status: 'connected' })
      .eq('id', row.id);
    return true;
  } catch {
    await db
      .from('linkedin_connections')
      .update({ status: 'reauthorization_required' })
      .eq('id', row.id);
    return false;
  }
}

/**
 * Never claims a silent refresh unless a refresh token actually exists — this
 * OIDC tier almost never issues one, so the common return is
 * `{ refreshed: false, reason: 'no_refresh_token' }`, and the caller should
 * surface "reconnect" rather than retrying.
 */
export async function refreshAuthorization(
  userId: string,
): Promise<{ refreshed: boolean; reason?: string }> {
  const { data } = await db
    .from('linkedin_connections')
    .select('id, encrypted_refresh_token')
    .eq('user_id', userId)
    .maybeSingle();
  const row = data as Pick<ConnectionRow, 'id' | 'encrypted_refresh_token'> | null;
  if (!row || !row.encrypted_refresh_token) {
    return { refreshed: false, reason: 'no_refresh_token' };
  }

  const { clientId, clientSecret } = requireConfig();
  try {
    const body = new URLSearchParams({
      grant_type: 'refresh_token',
      refresh_token: decryptSecret(row.encrypted_refresh_token),
      client_id: clientId,
      client_secret: clientSecret,
    });
    const resp = await fetch(TOKEN_ENDPOINT, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: body.toString(),
    });
    if (!resp.ok) throw new Error(`refresh failed (${resp.status})`);
    const tokens = (await resp.json()) as TokenResponse;
    const now = Date.now();
    await db
      .from('linkedin_connections')
      .update({
        encrypted_access_token: encryptSecret(tokens.access_token),
        access_token_expires_at: new Date(now + tokens.expires_in * 1000).toISOString(),
        status: 'connected',
      })
      .eq('id', row.id);
    return { refreshed: true };
  } catch {
    await db
      .from('linkedin_connections')
      .update({ status: 'reauthorization_required' })
      .eq('id', row.id);
    return { refreshed: false, reason: 'refresh_failed' };
  }
}

/** LinkedIn has no revoke endpoint at this product tier, so "disconnect" means
 *  forgetting our own copy of the tokens — stated honestly, not framed as
 *  revoking access on LinkedIn's side. */
export async function disconnect(userId: string): Promise<void> {
  const { error } = await db
    .from('linkedin_connections')
    .update({
      status: 'disconnected',
      encrypted_access_token: '',
      encrypted_refresh_token: null,
      disconnected_at: new Date().toISOString(),
    })
    .eq('user_id', userId);
  if (error) throw httpError(500, 'Failed to disconnect LinkedIn');
}
