import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import toast from 'react-hot-toast';
import { Layout } from '../components/Layout';
import { Modal } from '../components/Modal';
import { api } from '../services/api';
import { ComplianceReportButton } from '../components/TrainingCompliance';
import { SkeletonCard } from '../components/Skeleton';
import { useAuth } from '../context/AuthContext';
import { MANAGER_TIER } from '../types';
import { Button } from '../components/Button';

/**
 * I-983 STEM-OPT "Training Plan for STEM OPT Students" view.
 *
 * Renders the assignment + course as an audit-ready training plan with the
 * exact section layout DHS uses on Form I-983:
 *
 *   Section 1 — Student information (assigned consultant)
 *   Section 2 — Employer information (EIN, E-Verify #, supervisor)
 *   Section 3 — Employment information (start/end dates, hours, wage)
 *   Section 5 — Training plan goals and objectives + oversight + assessment
 *   Section 6 — Knowledge / skills / techniques the student will learn
 *
 *   Plus the two mandatory evaluations (12-month self + final), which the
 *   student fills in from their own view of this page.
 *
 * Manager-tier sees + edits the employer/wage/STEM block. Consultants can
 * read it and submit their own SELF_12_MONTH + FINAL evaluations.
 */
export function TrainingPlanView() {
  const { id } = useParams<{ id: string }>();
  const { profile } = useAuth();
  const isManager = !!profile && (MANAGER_TIER as string[]).includes(profile.role);
  const [assignment, setAssignment] = useState<any | null>(null);
  const [course, setCourse] = useState<any | null>(null);
  const [evals, setEvals] = useState<any[]>([]);
  const [editOpen, setEditOpen] = useState(false);
  const [evalOpen, setEvalOpen] = useState<null | 'SELF_12_MONTH' | 'FINAL' | 'SUPERVISOR_INTERIM'>(
    null,
  );

  async function load() {
    if (!id) return;
    try {
      const [a, e] = await Promise.all([
        api.get(`/training/assignments/${id}`),
        api.get(`/training/assignments/${id}/evaluations`),
      ]);
      setAssignment(a.data);
      setEvals(e.data ?? []);
      const cr = await api.get(`/training/courses/${a.data.course_id}`);
      setCourse(cr.data);
    } catch (err: any) {
      toast.error(err?.response?.data?.error ?? 'Failed to load training plan');
    }
  }
  useEffect(() => {
    load(); /* eslint-disable-next-line */
  }, [id]);

  if (!assignment || !course) {
    return (
      <Layout title="Training plan">
        <div className="space-y-4">
          <SkeletonCard lines={4} />
          <SkeletonCard lines={6} />
        </div>
      </Layout>
    );
  }

  const a = assignment;
  const c = course;
  const student = a.assignee ?? {};

  return (
    <Layout
      title="I-983 Training Plan"
      crumbs={[
        { label: 'Workspace', to: '/dashboard' },
        { label: 'Training', to: '/training' },
        { label: 'Plan' },
      ]}
    >
      <div className="max-w-4xl">
        {/* Action bar (hidden when printed) */}
        <div className="flex items-center justify-between mb-4 print:hidden">
          <div>
            <h1 className="text-2xl font-semibold tracking-tight">I-983 Training Plan</h1>
            <p className="text-xs text-muted mt-0.5">
              STEM-OPT training plan for {student.full_name ?? student.email ?? 'student'} ·{' '}
              {c.title}
            </p>
          </div>
          <div className="flex items-center gap-2">
            <Link
              to={`/training/assignments/${a.id}`}
              className="border border-border text-ink text-sm px-3 py-1.5 rounded-lg hover:bg-hover"
            >
              ← Back to course
            </Link>
            <Button variant="outline" onClick={() => window.print()}>
              Print / save PDF
            </Button>
            {id && <ComplianceReportButton assignmentId={id} />}
            {isManager && (
              <Button variant="primary" onClick={() => setEditOpen(true)}>
                Edit attestation
              </Button>
            )}
          </div>
        </div>

        <div className="bg-surface border border-border rounded-2xl p-8 space-y-8 print:border-none print:rounded-none">
          {/* Header */}
          <header className="border-b border-border pb-4">
            <div className="text-[10px] font-semibold uppercase tracking-widest text-emerald-700 dark:text-emerald-300">
              DHS Form I-983 · Training Plan for STEM OPT Students
            </div>
            <h2 className="text-xl font-bold mt-1">{c.title}</h2>
            <p className="text-xs text-muted mt-1">
              This page is generated by HireOrbit AI from the training assignment record. It is
              intended as the working copy of the I-983 — print and sign for the official DHS
              submission.
            </p>
          </header>

          {/* Section 1 — Student */}
          <Section number="1" title="Student information">
            <Grid>
              <Field k="Name" v={student.full_name} />
              <Field k="Email" v={student.email} />
              <Field k="Role" v={student.role} />
              <Field
                k="Degree level + field"
                v={a.stem_degree}
                placeholder="e.g. MS Computer Science"
              />
              <Field k="CIP code" v={a.stem_cip_code} placeholder="e.g. 11.0701" />
            </Grid>
          </Section>

          {/* Section 2 — Employer */}
          <Section number="2" title="Employer information">
            <Grid>
              <Field k="Employer name" v={a.employer_name} placeholder="Legal company name" />
              <Field
                k="Employer address"
                v={a.employer_address}
                placeholder="Street, city, state, ZIP"
              />
              <Field k="EIN" v={a.employer_ein} placeholder="IRS Employer ID Number" />
              <Field
                k="E-Verify number"
                v={a.employer_everify_no}
                placeholder="Required for STEM-OPT"
              />
              <Field k="Supervisor name" v={a.supervisor_name} />
              <Field k="Supervisor title" v={a.supervisor_title} />
              <Field k="Supervisor email" v={a.supervisor_email} />
            </Grid>
          </Section>

          {/* Section 3 — Employment */}
          <Section number="3" title="Employment information">
            <Grid>
              <Field k="Start date" v={a.training_start_date} />
              <Field k="End date" v={a.training_end_date} />
              <Field k="Hours / week" v={a.weekly_hours} />
              <Field
                k="Wage"
                v={a.wage_amount ? `$${a.wage_amount} (${a.wage_basis ?? '—'})` : null}
              />
            </Grid>
            <p className="text-[11px] text-muted mt-2">
              Wage must be commensurate with similarly-situated U.S. workers per DHS rules.
            </p>
          </Section>

          {/* Section 5 — Goals + oversight + assessment */}
          <Section number="5" title="Training plan: goals, oversight, and assessment">
            <Subsection title="Goals and objectives">
              {c.learning_objectives?.length ? (
                <ul className="list-disc list-outside pl-5 space-y-1 text-sm text-ink">
                  {c.learning_objectives.map((o: string) => (
                    <li key={o}>{o}</li>
                  ))}
                </ul>
              ) : (
                <Empty>Add learning objectives on the course to populate this section.</Empty>
              )}
            </Subsection>

            <Subsection title="How the employer will provide oversight + supervision">
              {a.oversight_method ? (
                <p className="text-sm text-ink whitespace-pre-wrap">{a.oversight_method}</p>
              ) : (
                <Empty>Manager-tier: edit attestation to describe the oversight cadence.</Empty>
              )}
            </Subsection>

            <Subsection title="Methods used to measure performance">
              {c.assessment_methods?.length ? (
                <ul className="list-disc list-outside pl-5 space-y-1 text-sm text-ink">
                  {c.assessment_methods.map((m: string) => (
                    <li key={m}>{m}</li>
                  ))}
                </ul>
              ) : (
                <Empty>Add assessment methods on the course to populate this section.</Empty>
              )}
            </Subsection>
          </Section>

          {/* Section 6 — Knowledge / skills / techniques */}
          <Section number="6" title="Knowledge, skills, and techniques the student will acquire">
            {c.stem_relevance && <p className="text-sm text-ink mb-3">{c.stem_relevance}</p>}
            {c.skills_taught?.length ? (
              <div className="flex flex-wrap gap-1.5">
                {c.skills_taught.map((s: string) => (
                  <span key={s} className="text-[11px] bg-hover text-ink px-2 py-0.5 rounded-full">
                    {s}
                  </span>
                ))}
              </div>
            ) : (
              <Empty>Add skills/techniques on the course to populate this section.</Empty>
            )}
          </Section>

          {/* Evaluations */}
          <Section number="E" title="Evaluations (12-month self + final)">
            <div className="space-y-3">
              {evals.length === 0 && <Empty>No evaluations yet.</Empty>}
              {evals.map((ev) => (
                <article key={ev.id} className="bg-hover border border-border rounded-lg p-4">
                  <div className="flex items-center justify-between flex-wrap gap-2">
                    <div className="text-[10px] font-semibold uppercase tracking-widest text-muted">
                      {ev.kind.replace('_', ' ')} · {ev.evaluation_date}
                    </div>
                    {typeof ev.hours_completed === 'number' && (
                      <div className="text-[11px] text-muted">{ev.hours_completed} h completed</div>
                    )}
                  </div>
                  {ev.goals_progress && (
                    <ReadField label="Progress against objectives" value={ev.goals_progress} />
                  )}
                  {ev.skills_acquired && (
                    <ReadField label="Skills / techniques acquired" value={ev.skills_acquired} />
                  )}
                  {ev.supervisor_notes && (
                    <ReadField label="Supervisor narrative" value={ev.supervisor_notes} />
                  )}
                  {typeof ev.rating === 'number' && (
                    <ReadField label="Supervisor rating (1–5)" value={String(ev.rating)} />
                  )}
                  <div className="grid md:grid-cols-2 gap-3 mt-3 text-[11px] text-muted">
                    <div>
                      Student signature:{' '}
                      <span className="text-ink">{ev.student_signature_name || '—'}</span>{' '}
                      {ev.student_signed_at &&
                        ` (${new Date(ev.student_signed_at).toLocaleDateString()})`}
                    </div>
                    <div>
                      Supervisor signature:{' '}
                      <span className="text-ink">{ev.supervisor_signature_name || '—'}</span>{' '}
                      {ev.supervisor_signed_at &&
                        ` (${new Date(ev.supervisor_signed_at).toLocaleDateString()})`}
                    </div>
                  </div>
                </article>
              ))}
            </div>

            <div className="flex flex-wrap gap-2 mt-4 print:hidden">
              <Button variant="ghost" size="sm" onClick={() => setEvalOpen('SELF_12_MONTH')}>
                + 12-month self-evaluation
              </Button>
              <Button variant="ghost" size="sm" onClick={() => setEvalOpen('FINAL')}>
                + Final evaluation
              </Button>
              {isManager && (
                <Button variant="ghost" size="sm" onClick={() => setEvalOpen('SUPERVISOR_INTERIM')}>
                  + Supervisor interim note
                </Button>
              )}
            </div>
          </Section>
        </div>
      </div>

      {isManager && (
        <EditAttestationModal
          open={editOpen}
          onClose={() => setEditOpen(false)}
          assignmentId={a.id}
          initial={a}
          onSaved={load}
        />
      )}
      {evalOpen && (
        <EvaluationModal
          open
          onClose={() => setEvalOpen(null)}
          assignmentId={a.id}
          kind={evalOpen}
          studentName={student.full_name ?? ''}
          isManager={isManager}
          onSaved={() => {
            setEvalOpen(null);
            load();
          }}
        />
      )}
    </Layout>
  );
}

// ---------- Layout primitives ----------
function Section({ number, title, children }: { number: string; title: string; children: any }) {
  return (
    <section>
      <h3 className="text-sm font-semibold tracking-tight flex items-baseline gap-2 mb-3">
        <span className="text-[10px] font-semibold uppercase tracking-widest text-emerald-700 dark:text-emerald-300">
          Section {number}
        </span>
        <span>{title}</span>
      </h3>
      {children}
    </section>
  );
}
function Subsection({ title, children }: { title: string; children: any }) {
  return (
    <div className="mb-4">
      <div className="text-[10px] font-semibold uppercase tracking-widest text-muted mb-1">
        {title}
      </div>
      {children}
    </div>
  );
}
function Grid({ children }: { children: any }) {
  return <div className="grid md:grid-cols-2 gap-3">{children}</div>;
}
function Field({ k, v, placeholder }: { k: string; v: any; placeholder?: string }) {
  return (
    <div className="border border-border rounded-md px-3 py-2 bg-slate-50/50">
      <div className="text-[10px] font-semibold uppercase tracking-widest text-muted">{k}</div>
      <div className="text-sm text-ink break-words">
        {v ? String(v) : <span className="italic text-muted">{placeholder ?? '—'}</span>}
      </div>
    </div>
  );
}
function ReadField({ label, value }: { label: string; value: string }) {
  return (
    <div className="mt-2">
      <div className="text-[10px] font-semibold uppercase tracking-widest text-muted">{label}</div>
      <p className="text-sm text-ink whitespace-pre-wrap">{value}</p>
    </div>
  );
}
function Empty({ children }: { children: any }) {
  return <p className="text-[12px] italic text-muted">{children}</p>;
}

// ---------- Edit attestation modal ----------
function EditAttestationModal({
  open,
  onClose,
  assignmentId,
  initial,
  onSaved,
}: {
  open: boolean;
  onClose: () => void;
  assignmentId: string;
  initial: any;
  onSaved: () => void;
}) {
  const [f, setF] = useState<any>({});
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (!open) return;
    setF({
      employer_name: initial.employer_name ?? '',
      employer_address: initial.employer_address ?? '',
      employer_ein: initial.employer_ein ?? '',
      employer_everify_no: initial.employer_everify_no ?? '',
      supervisor_name: initial.supervisor_name ?? '',
      supervisor_title: initial.supervisor_title ?? '',
      supervisor_email: initial.supervisor_email ?? '',
      oversight_method: initial.oversight_method ?? '',
      wage_amount: initial.wage_amount ?? '',
      wage_basis: initial.wage_basis ?? 'HOURLY',
      weekly_hours: initial.weekly_hours ?? '',
      stem_degree: initial.stem_degree ?? '',
      stem_cip_code: initial.stem_cip_code ?? '',
      training_start_date: initial.training_start_date ?? '',
      training_end_date: initial.training_end_date ?? '',
    });
  }, [open, initial]);

  async function save() {
    setSaving(true);
    try {
      await api.put(`/training/assignments/${assignmentId}`, {
        ...f,
        wage_amount: f.wage_amount ? Number(f.wage_amount) : null,
        weekly_hours: f.weekly_hours ? Number(f.weekly_hours) : null,
        training_start_date: f.training_start_date || null,
        training_end_date: f.training_end_date || null,
      });
      toast.success('Attestation saved');
      onSaved();
    } catch (e: any) {
      toast.error(e?.response?.data?.error ?? 'Failed to save');
    } finally {
      setSaving(false);
    }
  }

  return (
    <Modal
      open={open}
      onClose={onClose}
      title="Edit I-983 attestation"
      footer={
        <Button variant="primary" onClick={save} disabled={saving} loading={saving}>
          {saving ? 'Saving…' : 'Save'}
        </Button>
      }
    >
      <div className="grid grid-cols-2 gap-3">
        <FInput
          label="Employer name"
          value={f.employer_name}
          onChange={(v) => setF({ ...f, employer_name: v })}
        />
        <FInput
          label="Employer address"
          value={f.employer_address}
          onChange={(v) => setF({ ...f, employer_address: v })}
        />
        <FInput
          label="EIN"
          value={f.employer_ein}
          onChange={(v) => setF({ ...f, employer_ein: v })}
        />
        <FInput
          label="E-Verify number"
          value={f.employer_everify_no}
          onChange={(v) => setF({ ...f, employer_everify_no: v })}
        />
        <FInput
          label="Supervisor name"
          value={f.supervisor_name}
          onChange={(v) => setF({ ...f, supervisor_name: v })}
        />
        <FInput
          label="Supervisor title"
          value={f.supervisor_title}
          onChange={(v) => setF({ ...f, supervisor_title: v })}
        />
        <FInput
          label="Supervisor email"
          value={f.supervisor_email}
          onChange={(v) => setF({ ...f, supervisor_email: v })}
          type="email"
        />
        <FInput
          label="STEM degree"
          value={f.stem_degree}
          onChange={(v) => setF({ ...f, stem_degree: v })}
        />
        <FInput
          label="CIP code"
          value={f.stem_cip_code}
          onChange={(v) => setF({ ...f, stem_cip_code: v })}
        />
        <FInput
          label="Weekly hours"
          value={f.weekly_hours}
          onChange={(v) => setF({ ...f, weekly_hours: v })}
          type="number"
        />
        <FInput
          label="Wage amount"
          value={f.wage_amount}
          onChange={(v) => setF({ ...f, wage_amount: v })}
          type="number"
        />
        <FSelect
          label="Wage basis"
          value={f.wage_basis}
          onChange={(v) => setF({ ...f, wage_basis: v })}
          options={['HOURLY', 'SALARY']}
        />
        <FInput
          label="Training start"
          value={f.training_start_date}
          onChange={(v) => setF({ ...f, training_start_date: v })}
          type="date"
        />
        <FInput
          label="Training end"
          value={f.training_end_date}
          onChange={(v) => setF({ ...f, training_end_date: v })}
          type="date"
        />
        <div className="col-span-2">
          <FTextArea
            label="Oversight method (how the employer monitors progress)"
            value={f.oversight_method}
            onChange={(v) => setF({ ...f, oversight_method: v })}
            rows={4}
          />
        </div>
      </div>
    </Modal>
  );
}

// ---------- Evaluation modal ----------
function EvaluationModal({
  open,
  onClose,
  assignmentId,
  kind,
  studentName,
  isManager,
  onSaved,
}: {
  open: boolean;
  onClose: () => void;
  assignmentId: string;
  kind: 'SELF_12_MONTH' | 'FINAL' | 'SUPERVISOR_INTERIM';
  studentName: string;
  isManager: boolean;
  onSaved: () => void;
}) {
  const [f, setF] = useState<any>({
    evaluation_date: new Date().toISOString().slice(0, 10),
    goals_progress: '',
    skills_acquired: '',
    hours_completed: '',
    supervisor_notes: '',
    rating: '',
    student_signature_name: '',
    supervisor_signature_name: '',
  });
  const [saving, setSaving] = useState(false);

  const titleMap = {
    SELF_12_MONTH: '12-month self-evaluation',
    FINAL: 'Final evaluation',
    SUPERVISOR_INTERIM: 'Supervisor interim note',
  } as const;

  async function save() {
    setSaving(true);
    try {
      const body: any = {
        kind,
        evaluation_date: f.evaluation_date || undefined,
        goals_progress: f.goals_progress || null,
        skills_acquired: f.skills_acquired || null,
        hours_completed: f.hours_completed ? Number(f.hours_completed) : null,
        supervisor_notes: f.supervisor_notes || null,
        rating: f.rating ? Number(f.rating) : null,
      };
      // Stamp signatures at save-time.
      if (f.student_signature_name) {
        body.student_signature_name = f.student_signature_name;
        body.student_signed_at = new Date().toISOString();
      }
      if (f.supervisor_signature_name) {
        body.supervisor_signature_name = f.supervisor_signature_name;
        body.supervisor_signed_at = new Date().toISOString();
      }
      await api.post(`/training/assignments/${assignmentId}/evaluations`, body);
      toast.success('Evaluation submitted');
      onSaved();
    } catch (e: any) {
      toast.error(e?.response?.data?.error ?? 'Failed to submit');
    } finally {
      setSaving(false);
    }
  }

  return (
    <Modal
      open={open}
      onClose={onClose}
      title={titleMap[kind]}
      footer={
        <Button variant="primary" onClick={save} disabled={saving} loading={saving}>
          {saving ? 'Submitting…' : 'Submit'}
        </Button>
      }
    >
      <div className="space-y-3">
        <FInput
          label="Evaluation date"
          type="date"
          value={f.evaluation_date}
          onChange={(v) => setF({ ...f, evaluation_date: v })}
        />
        <FTextArea
          label="Progress against goals + objectives"
          value={f.goals_progress}
          onChange={(v) => setF({ ...f, goals_progress: v })}
          rows={4}
        />
        <FTextArea
          label="Specific knowledge / skills / techniques acquired"
          value={f.skills_acquired}
          onChange={(v) => setF({ ...f, skills_acquired: v })}
          rows={4}
        />
        <FInput
          label="Hours completed in this period"
          type="number"
          value={f.hours_completed}
          onChange={(v) => setF({ ...f, hours_completed: v })}
        />

        {(kind === 'FINAL' || kind === 'SUPERVISOR_INTERIM') && isManager && (
          <>
            <FTextArea
              label="Supervisor narrative"
              value={f.supervisor_notes}
              onChange={(v) => setF({ ...f, supervisor_notes: v })}
              rows={3}
            />
            <FInput
              label="Performance rating (1–5)"
              type="number"
              value={f.rating}
              onChange={(v) => setF({ ...f, rating: v })}
            />
          </>
        )}

        <div className="grid grid-cols-2 gap-3 pt-2 border-t border-border">
          <FInput
            label="Student signature (print name)"
            value={f.student_signature_name}
            onChange={(v) => setF({ ...f, student_signature_name: v })}
            hint={studentName ? `e.g. ${studentName}` : undefined}
          />
          {isManager && (
            <FInput
              label="Supervisor signature (print name)"
              value={f.supervisor_signature_name}
              onChange={(v) => setF({ ...f, supervisor_signature_name: v })}
            />
          )}
        </div>
      </div>
    </Modal>
  );
}

function FInput({
  label,
  value,
  onChange,
  type = 'text',
  hint,
}: {
  label: string;
  value: any;
  onChange: (v: string) => void;
  type?: string;
  hint?: string;
}) {
  return (
    <label className="block">
      <span className="text-[10px] font-semibold uppercase tracking-widest text-muted">
        {label}
      </span>
      <input
        type={type}
        value={value ?? ''}
        onChange={(e) => onChange(e.target.value)}
        className="mt-1 w-full text-sm border border-border rounded-md px-2 py-1.5"
      />
      {hint && <p className="text-[10px] text-muted mt-0.5">{hint}</p>}
    </label>
  );
}
function FTextArea({
  label,
  value,
  onChange,
  rows = 3,
}: {
  label: string;
  value: any;
  onChange: (v: string) => void;
  rows?: number;
}) {
  return (
    <label className="block">
      <span className="text-[10px] font-semibold uppercase tracking-widest text-muted">
        {label}
      </span>
      <textarea
        rows={rows}
        value={value ?? ''}
        onChange={(e) => onChange(e.target.value)}
        className="mt-1 w-full text-sm border border-border rounded-md px-2 py-1.5"
      />
    </label>
  );
}
function FSelect({
  label,
  value,
  onChange,
  options,
}: {
  label: string;
  value: string;
  onChange: (v: string) => void;
  options: string[];
}) {
  return (
    <label className="block">
      <span className="text-[10px] font-semibold uppercase tracking-widest text-muted">
        {label}
      </span>
      <select
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className="mt-1 w-full text-sm border border-border rounded-md px-2 py-1.5 bg-surface"
      >
        {options.map((o) => (
          <option key={o} value={o}>
            {o}
          </option>
        ))}
      </select>
    </label>
  );
}
